<#
.SYNOPSIS
    Generates ServerFiles.wxs fragment from server/build directory.
    Run this whenever server/build content changes.

.EXAMPLE
    .\Generate-ServerFiles.ps1
#>

$ErrorActionPreference = "Stop"

$scriptDir = $PSScriptRoot
$serverBuildDir = Resolve-Path "$scriptDir\..\..\server\build"
$outputFile = Join-Path $scriptDir "ServerFiles.wxs"

Write-Host "Scanning: $serverBuildDir" -ForegroundColor Cyan

# Collect all files with relative paths
$files = Get-ChildItem -Path $serverBuildDir -Recurse -File |
    Sort-Object FullName |
    ForEach-Object {
        $relativePath = $_.FullName.Substring($serverBuildDir.Path.Length).TrimStart('\', '/')
        $relativePath = $relativePath -replace '/', '\'
        $directory = [System.IO.Path]::GetDirectoryName($relativePath)
        if ([string]::IsNullOrWhiteSpace($directory)) { $directory = "" }

        [PSCustomObject]@{
            RelativePath = $relativePath
            Directory    = $directory
        }
    }

# Get unique subdirectories
$subDirs = $files |
    ForEach-Object { $_.Directory } |
    Where-Object { -not [string]::IsNullOrWhiteSpace($_) } |
    Sort-Object -Unique

# Generate safe WiX identifiers
function Get-SafeId($path) {
    $id = $path -replace '[^a-zA-Z0-9_.]', '_'
    $id = $id -replace '\.', '_'
    return $id
}

# Build the WXS content
$xml = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED by Generate-ServerFiles.ps1 - DO NOT EDIT MANUALLY -->
<!-- Re-run .\Generate-ServerFiles.ps1 when server/build content changes -->

<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <ComponentGroup Id="ServerBuildFiles">
"@

$counter = 0
foreach ($file in $files) {
    $counter++
    $safeId = Get-SafeId $file.RelativePath
    $directoryId = if ([string]::IsNullOrWhiteSpace($file.Directory)) {
        "DIR_Server"
    } else {
        "DIR_Server_$(Get-SafeId $file.Directory)"
    }

    $xml += @"

      <Component Id="SrvComp_$safeId" Directory="$directoryId" Guid="*">
        <File Source="`$(var.ServerBuildDir)\$($file.RelativePath)" KeyPath="yes" />
      </Component>
"@
}

$xml += @"

    </ComponentGroup>
  </Fragment>

  <Fragment>
    <DirectoryRef Id="DIR_Server">
"@

# Build directory tree
$dirTree = @{}
foreach ($dir in $subDirs) {
    $parts = $dir -split '[/\\]'
    $currentPath = ""
    for ($i = 0; $i -lt $parts.Length; $i++) {
        $parentPath = $currentPath
        $currentPath = if ($currentPath) { "$currentPath\$($parts[$i])" } else { $parts[$i] }
        if (-not $dirTree.ContainsKey($currentPath)) {
            $dirTree[$currentPath] = $parentPath
        }
    }
}

function Write-DirTree($parentPath, $indent) {
    $children = $dirTree.Keys | Where-Object { $dirTree[$_] -eq $parentPath } | Sort-Object
    foreach ($child in $children) {
        $dirName = ($child -split '[/\\]')[-1]
        $safeId = Get-SafeId $child
        $script:xml += "`n$indent<Directory Id=`"DIR_Server_$safeId`" Name=`"$dirName`">"
        Write-DirTree $child "$indent  "
        $script:xml += "`n$indent</Directory>"
    }
}

Write-DirTree "" "      "

$xml += @"

    </DirectoryRef>
  </Fragment>
</Wix>
"@

$xml | Out-File -FilePath $outputFile -Encoding UTF8
Write-Host "Generated: $outputFile ($counter files, $($subDirs.Count) directories)" -ForegroundColor Green
