<#
.SYNOPSIS
    Generates ServerNodeModules.wxs fragment from server/node_modules (production deps only).
    Run after: npm ci and npm prune (production deps) in server/

.EXAMPLE
    .\Generate-ServerNodeModules.ps1
#>

$ErrorActionPreference = "Stop"

$scriptDir = $PSScriptRoot
$nodeModulesDir = Join-Path $scriptDir "..\..\server\node_modules" | Resolve-Path -ErrorAction Stop
$outputFile = Join-Path $scriptDir "ServerNodeModules.wxs"

Write-Host "Scanning: $nodeModulesDir" -ForegroundColor Cyan

$files = Get-ChildItem -Path $nodeModulesDir -Recurse -File |
    Sort-Object FullName |
    ForEach-Object {
        $relativePath = $_.FullName.Substring($nodeModulesDir.Path.Length).TrimStart('\', '/')
        $relativePath = $relativePath -replace '/', '\'
        $directory = [System.IO.Path]::GetDirectoryName($relativePath)
        if ([string]::IsNullOrWhiteSpace($directory)) { $directory = "" }

        [PSCustomObject]@{
            RelativePath = $relativePath
            Directory    = $directory
        }
    }

function Get-DirParent([string]$fullPath) {
    if ([string]::IsNullOrWhiteSpace($fullPath)) { return $null }
    $p = [System.IO.Path]::GetDirectoryName($fullPath)
    if ([string]::IsNullOrWhiteSpace($p)) { return "" }
    return $p
}

# Full relative paths of every folder under node_modules (Ids must be unique; sanitized names collide e.g. v4-mini vs v4\mini)
$dirsSeen = @{}
foreach ($file in $files) {
    $d = $file.Directory
    while (-not [string]::IsNullOrWhiteSpace($d)) {
        $dirsSeen[$d] = $true
        $parent = Get-DirParent $d
        if ([string]::IsNullOrWhiteSpace($parent)) { break }
        $d = $parent
    }
}

$sortedDirs = @($dirsSeen.Keys | Sort-Object)
$dirToWiXId = @{}
$dirSeq = 0
foreach ($d in $sortedDirs) {
    $dirSeq++
    $dirToWiXId[$d] = "DIR_SNM_d{0:D6}" -f $dirSeq
}

$xml = @"
<?xml version="1.0" encoding="UTF-8"?>
<!-- AUTO-GENERATED by Generate-ServerNodeModules.ps1. Do not edit manually. -->
<!-- Re-run after npm prune leaves production deps in server/node_modules. -->

<Wix xmlns="http://wixtoolset.org/schemas/v4/wxs">
  <Fragment>
    <ComponentGroup Id="ServerNodeModulesFiles">
"@

$fileSeq = 0
foreach ($file in $files) {
    $fileSeq++
    $compId = "SrvNm_f{0:D7}" -f $fileSeq
    $directoryId = if ([string]::IsNullOrWhiteSpace($file.Directory)) {
        "DIR_Server_node_modules"
    } else {
        $dirToWiXId[$file.Directory]
    }

    $xml += @"

      <Component Id="$compId" Directory="$directoryId" Guid="*">
        <File Source="`$(var.ServerNodeModulesDir)\$($file.RelativePath)" KeyPath="yes" />
      </Component>
"@
}

$xml += @"

    </ComponentGroup>
  </Fragment>

  <Fragment>
    <DirectoryRef Id="DIR_Server">
      <Directory Id="DIR_Server_node_modules" Name="node_modules">
"@

function Get-DirTreeXml {
    param([string]$ParentKey, [string]$Indent)

    $children = $sortedDirs | Where-Object { (Get-DirParent $_) -eq $ParentKey } | Sort-Object
    $sb = [System.Text.StringBuilder]::new()
    foreach ($child in $children) {
        $dirName = [System.IO.Path]::GetFileName($child)
        if ([string]::IsNullOrWhiteSpace($dirName)) { continue }
        $safeName = $dirName -replace '&', '&amp;' -replace '"', '&quot;'
        $wid = $dirToWiXId[$child]
        [void]$sb.AppendLine("$Indent<Directory Id=`"$wid`" Name=`"$safeName`">")
        [void]$sb.Append((Get-DirTreeXml -ParentKey $child -Indent "$Indent  "))
        [void]$sb.AppendLine("$Indent</Directory>")
    }
    return $sb.ToString()
}

$xml += Get-DirTreeXml -ParentKey "" -Indent "        "

$xml += @"

      </Directory>
    </DirectoryRef>
  </Fragment>
</Wix>
"@

$xml | Out-File -FilePath $outputFile -Encoding UTF8
Write-Host "Generated: $outputFile ($fileSeq files, $($sortedDirs.Count) directories)" -ForegroundColor Green
